---
kind: pipeline
type: docker
name: 7hills

workspace:
  path: /home/deployr/7hills

steps:
- name: deploy backend
  image: docker/compose:1.29.1
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  # - docker-compose -f docker-compose.back.yml build --pull
  - docker-compose -f docker-compose.back.yml up -d

- name: deploy frontend
  image: docker/compose:1.29.1
  environment:
    SPRAPI_API_URL: https://api.linus.cx
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker-compose -f docker-compose.front.yml build --pull
  - docker-compose -f docker-compose.front.yml up -d


volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

...
