---
kind: pipeline
type: docker
name: 7hills

workspace:
  path: /home/deployr/7hills

steps:
- name: build backend
  image: docker/compose:1.29.2
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker-compose -f docker-compose.back.yml build --pull
  when:
    event:
    - push
    - pull_request

- name: deploy backend
  image: docker/compose:1.29.2
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker-compose -f docker-compose.back.yml up -d
  when:
    branch:
    - master
    event:
    - push

- name: build frontend (with cache)
  image: docker/compose:1.29.2
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker-compose -f docker-compose.front.yml build --pull
  when:
    event:
    - push
    - pull_request

- name: build frontend (without cache)
  image: docker/compose:1.29.2
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker-compose -f docker-compose.front.yml build --pull --no-cache
  when:
    event:
    - cron

- name: deploy analytics
  image: docker/compose:1.29.2
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker-compose -f docker-compose.front.yml up -d
  when:
    branch:
    - master
    event:
    - cron
    - push

- name: prune images
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker system prune -f
  when:
    event:
    - cron

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

...
