---
kind: pipeline
type: docker
name: 7hills

workspace:
  path: /home/deployr/7hills

steps:
- name: build backend
  image: docker/compose:1.29.1
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker-compose -f docker-compose.back.yml build --pull

- name: deploy backend
  image: docker/compose:1.29.1
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker-compose -f docker-compose.back.yml up -d
  when:
    branch:
    - master
    event:
    - push

- name: build frontend
  image: docker/compose:1.29.1
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker-compose -f docker-compose.front.yml build --pull --no-cache

- name: deploy frontend
  image: docker/compose:1.29.1
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker-compose -f docker-compose.front.yml up -d
  when:
    branch:
    - master
    event:
    - push

- name: prune images
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker system prune -f

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

...
