---
version: '3'
services:
  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    ports:
      - "3002:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umami.rule=Host(`analytics.sevenhills-restaurant.de`)"
      - "traefik.http.routers.umami.entrypoints=https"
      - "traefik.http.routers.umami.tls=true"
      - "traefik.http.routers.umami.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.umami-https.redirectscheme.scheme=https"
      - "traefik.http.routers.umami-http.entrypoints=http"
      - "traefik.http.routers.umami-http.rule=Host(`analytics.sevenhills-restaurant.de`)"
      - "traefik.http.routers.umami-http.middlewares=strapi-https@docker"
      - "traefik.http.routers.umami.middlewares=secHeaders@file"
      - "traefik.http.services.umami.loadbalancer.server.port=3002"
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - ./analytics-data:/var/lib/postgresql/data

networks:
  proxy:
    external:
      name: proxy
