---
version: "3"

services:
  # ===========================================================================
  # 7hills-back (https://api.sevenhills-restaurant.de)
  # ===========================================================================
  strapi:
    image: 7hills-back:main
    container_name: 7hills-back
    restart: always
    networks:
      - web
    expose:
      - "1337"
    volumes:
      - ./data:/home/node/app/data
      - ./uploads:/home/node/app/public/uploads

  7hills-front:
    image: 7hills-front:main
    container_name: 7hills-front
    restart: always
    networks:
      - web
    expose:
      - "3000"

networks:
  web:
    external: true
    name: web
