---
- name: Ensures traefik dir exists
  file:
    path: "{{ traefik_dir }}"
    state: directory
    mode: 0600

- name: Ensures acme.json file exists
  file:
    path: "{{ traefik_dir }}/acme.json"
    state: touch
    mode: 0600
    owner: "root"

- name: Adding dynamic.yml file
  template:
    src: dynamic.yml.j2
    dest: "{{ traefik_dir }}/dynamic.yml"
    mode: 0600
    owner: "root"

- name: Adding traefik.yml file
  template:
    src: traefik.yml.j2
    dest: "{{ traefik_dir }}/traefik.yml"
    mode: 0600
    owner: "root"

- name: Create the web network
  block:
    - name: web network
      docker_network:
        name: web

- name: Create the traefik container
  block:
    - name: traefik container
      docker_container:
        name: traefik
        image: "{{ traefik_image }}"
        restart_policy: unless-stopped
        recreate: true
        networks:
          - name: web
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - "{{ traefik_dir }}/traefik.yml:/etc/traefik/traefik.yml"
          - "{{ traefik_dir }}/dynamic.yml:/etc/traefik/dynamic.yml"
          - "{{ traefik_dir }}/acme.json:/etc/traefik/acme.json"
          - "/var/run/docker.sock:/var/run/docker.sock"
