---
- name: Setup server (install packages)
  hosts: all
  tasks:
    - name: Install essential packages
      apt:
        pkg:
          - "apparmor"
          - "borgbackup"
          - "borgmatic"
          - "curl"
          - "docker.io"
          - "docker-compose"
          - "git"
          - "rsync"
          - "sudo"
          - "vim"
        state: present
        update_cache: true

    - name: Put Caddyfile in place
      tags: deploy
      synchronize:
        src: Caddyfile
        dest: /root/caddy/Caddyfile

    - name: Create the web network
      tags: deploy
      docker_network:
        name: web

    - name: Copy docker-compose in place
      tags: deploy
      synchronize:
        src: docker-compose.yml
        dest: /root/docker-compose.yml

  tags:
    - packages
    - pkgs

- name: Setup server (configure the rest)
  hosts: all
  roles:
    - role: ansible-openssh
      tags: [hardening, openssh, ssh]
    - role: ansible-fail2ban
      tags: [hardening, fail2ban]
    - role: ansible-unattended-upgrades
      tags: [unattended-upgrades]
    - role: ansible-ctop
      tags: [docker, ctop]
