---
- name: Setup server (install packages)
  hosts: all
  tasks:
    - name: Install essential packages
      apt:
        pkg:
          - "borgbackup"
          - "borgmatic"
          - "curl"
          - "docker.io"
          - "docker-compose"
          - "git"
          - "rsync"
          - "sudo"
          - "vim"
        state: present
        update_cache: true
  tags:
    - packages
    - pkgs

- name: Setup server (configure the rest)
  hosts: all
  roles:
    - role: ansible-openssh
      tags: [hardening, openssh, ssh]
    - role: ansible-fail2ban
      tags: [hardening, fail2ban]
    - role: ansible-unattended-upgrades
      tags: [unattended-upgrades]
    - role: ansible-ctop
      tags: [docker, ctop]
