---
# ===========================================================================
# fail2ban
# ===========================================================================
fail2ban_destemail: "admin@bvpk.org"
fail2ban_sender: root@{{ ansible_fqdn }}
fail2ban_jail_configuration:
  - option: enabled
    value: "true"
    section: sshd
  - option: mode
    value: "aggressive"
    section: sshd

# ===========================================================================
# unattended-upgrades
# ===========================================================================
unattended_origins_patterns:
  - "origin=Ubuntu,archive=${distro_codename}-security"
  - "o=Ubuntu,a=${distro_codename}"
  - "o=Ubuntu,a=${distro_codename}-updates"
unattended_remove_unused_dependencies: true
unattended_mail: "admin@bvpk.org"
unattended_mail_only_on_error: true

# ===========================================================================
# docker(-compose)
# ===========================================================================
docker_compose_version: "1.29.2"

# ===========================================================================
# traefik
# ===========================================================================
traefik_image: traefik:2.5
traefik_dir: /srv/traefik
traefik_loglevel: WARN
tls_min_version: VersionTLS12
acme_email: "admin@bvpk.org"
