---
# ===========================================================================
# fail2ban
# ===========================================================================
fail2ban_destemail: "7hills@bsehn.dev"
fail2ban_sender: root@{{ ansible_fqdn }}
fail2ban_jail_configuration:
  - option: enabled
    value: "true"
    section: sshd
  - option: mode
    value: "aggressive"
    section: sshd

# ===========================================================================
# unattended-upgrades
# ===========================================================================
unattended_origins_patterns:
  # updates
  - "origin=Debian,codename=${distro_codename},label=Debian"
  # backwards compatibility
  - "origin=Debian,codename=${distro_codename},label=Debian-Security"
  # pattern for security releases, starting with bullseye
  - "origin=Debian,codename=${distro_codename}-security,label=Debian-Security"
unattended_remove_unused_dependencies: true
unattended_mail: "7hills@sehn.dev"
unattended_mail_only_on_error: true

# ===========================================================================
# docker(-compose)
# ===========================================================================
docker_compose_version: "1.29.2"
