---
kind: pipeline
type: docker
name: 7hills-next

clone:
  disable: true

steps:
  - name: clone with submodules
    image: alpine/git
    commands:
      - git clone https://git.lino.pw/linozen/7hills-next.git .
      - git submodule update --init --recursive --remote inventory

  - name: build
    image: willhallonline/ansible:2.9-buster-slim
    environment:
      SSH_KEY:
        from_secret: ssh_key
    commands:
      - apt-get update
      - apt-get install -y rsync
      - mkdir /root/.ssh && echo "$SSH_KEY" > /root/.ssh/id_ed25519 && chmod 0600 /root/.ssh/id_ed25519
      - ssh-keyscan -p 64299 -H 7hills-next.sehn.dev >> ~/.ssh/known_hosts
      - ssh deployr@7hills-next.sehn.dev -p 64299
      - ansible-playbook deploy.yml -i inventory/generate_inventory -l 7hills-next.sehn.dev -b -v
    when:
      branch: main
