---
- hosts: all
  remote_user: deployr

  tasks:
    - name: Backup current certificate store
      copy:
        src: /home/deployr/7hills-next/traefik/config/ACME/acme.json
        dest: /home/deployr/traefik.acme.json.bak
        remote_src: yes

    - name: Synchronize repo
      synchronize:
        delete: yes
        src: ./
        dest: /home/deployr/7hills-next

    - name: Make deployr owner
      shell: chown -R deployr:deployr /home/deployr/7hills-next

    - name: Make sure traefik config has the correct permissions
      file:
        path: /home/deployr/7hills-next/traefik/config/ACME/acme.json
        mode: 0600

    - name: Restore certificate store
      copy:
        src: /home/deployr/traefik.acme.json.bak
        dest: /home/deployr/7hills-next/traefik/config/ACME/acme.json
        remote_src: yes

    - name: Run docker-compose up
      shell: chdir=/home/deployr/7hills-next docker-compose up --build --detach
