#+TITLE: Notes

inspiration producers
https://www.dein-speisesalon.de/essen/unsere-philosophie/

* Text "Events"
** The Terrace
Stell dir vor, einen kühlen Drink zu genießen, während du Flugzeugen
aus allen Teilen des Kontinents bei Start und Landung zusiehst. Genau das ist
auf unserer ,,The Terrace‘‘ möglich – und weil schöne Erlebnisse noch schöner
werden, wenn man sie mit anderen Menschen teilt, lad doch einfach deine Freunde,
Familie oder Kollegen zu deiner nächsten Veranstaltung bei uns ein. Unser Seven
Hills Catering-Team setzt auf Nachhaltigkeit, lokales Flair und liebt es, für
dein nächstes Event über den Tellerrand hinauszuschauen um gemeinsam ein tolles
Genusserlebnis zu erschaffen.

** The Meetup
Du möchtest mehr als nur ein 08/15 Meeting? Dann bist du bei uns genau richtig.
Eine Runde Riesen Jenga auf unserer Terrasse oder eine Partie Tisch Kicker an
der Bar sorgen für genügend Abwechslung. Damit geben wir uns allerdings noch
nicht zufrieden. Unsere 5 Meeting Räume sind kreativ eingerichtet, verfügen über
die neueste Technik und sind flexibel aufteilbar. Den Rest besorgt unsere
einfallsreiche Crew, die aus deinem Meeting ein unvergessliches Erlebnis macht.
Probiere es aus und buch dein Meeting #atthemoxy.

Tagungspauschale ganztags, 69€ p.P.
Tagungspauschale halbtags, 59€ p.P.
Tagungspauschale halbtags ohne Lunch, 39€ p.P.

(Unsere Pauschalen beinhalten Raummiete, technisches Equipment, Detox-Wasser,
unbegrentzte Heißgetränke, 1 oder 2 Kaffeepause(n) und ein "Best of Seven Hills"
2-Gang-Menü im Restaurant.)

** The Contact
Wir wissen, dass du neugierig geworden bist. Melde dich für mehr Informationen
oder deine Anfrage bei unserem Sales Manager Benedict. Schreib ihm einfach eine
Mail oder ruf ihn doch direkt an!

Benedict Vandamme
Benedict.vandamme@ghotel.de
+49 173 5949493
* Text "Local"
Seven Hills - Sieben Erzeuger

Vulkanhof
Gillenfeld/Vulkaneifel

Entfernung:		83 km
Die Macher*innen:	Manuela Holtmann & ihr Team
Die Erfahrung:		1995 wurde der Hof komplett auf Ziegenhaltung mit einer angeschlossenen Käserei umgestellt - als eine der besten Käsereien ganz Deutschlands ausgezeichnet (Der Feinschmecker)

Die Erzeugnisse:
- Ziegenkäse aus der Vulkaneifel
- reines Naturprodukt
- Weiße Deutsche Edelziege & Bunte Deutsche Edelziege
- Geschmack des Ziegenkäses kommt von nahrhaften Gräsern und würzigen Kräutern der Eifelwiesen
- drei ganz wichtige Zutaten: Geduld, Handarbeit und langjährige Erfahrung
- im gesamten Herstellungsprozess wird bewusst auf Zusatzstoffe, Konservierungsmittel und Farbstoffe verzichtet


Margarethenhof
Andernach/Mayen-Koblenz

Entfernung:		52 km
Die Macher*innen:	Sarah Doetsch & Familie
Die Erfahrung:		seit fast 40 Jahren Charolais-Rinderzucht

Die Erzeugnisse:
- Charolais-Rinder aus eigener Zucht
- Tiere werden mit selbsterzeugtem Gras, Mais und Getreide schonend gefüttert
- Herden stehen je nach Wetterlage von April bis November/Dezember auf ca. 60 ha hofeigener Weidefläche in Andernach
- erst wenn das Tier seine natürliche Reife erreicht hat, wird der Schlachttermin festgelegt


Fischzucht & Angelpark Hahn
Wipperfürth/Oberbergischer Kreis

Entfernung:		38 km
Die Macher*innen:	Denis Hahn & Familie
Die Erfahrung:		Fischwirt in dritter Generation

Die Erzeugnisse:
- nachhaltige Fischzucht in 17 eigenen Teichen und Räucherei
- Aufzucht vom Ei bis zur Speisegröße in Bio-Aquakultur mit Quellwasser
- Forelle, Lachsforelle, Karpfen, Stör, Wels, Aal und Bachsaibling


Imkerei Bienwerk
Köln

Enternung:		14 km
Der Macher:		Frank Methien
Die Erfahrung:		Stadtimkerei seit 2010 mitten in die Kölner Südstadt

Die Erzeugnisse:
- reiner und unbehandelter Blütenhonig
- handgemachtes, hochwertiges Produkt
- große Vielfalt von Blumen und Bäumen verleiht dem Honig aus der Stadt eine Komplexität und Intensität die überrascht
- Kalternte und Extraktion


Feldhelden Rheinland
Pulheim-Stommeln/Rhein-Erft-Kreis

Entfernung:		32 km
Die Macher*innen:	Johannes, Thomas & Verena Decker
Die Erfahrung:		Feldhelden wurden 2019 gegründet – der Landwirtschaftsbetrieb wird seit über 200 Jahren von der Familie Decker betrieben

Die Erzeugnisse:
- das erste Kinoa aus dem Rheinland
- dank hochwertiger Proteine, Vitamine und Mineralstoffe positive Wirkung auf Körper, Geist und Seele
- kurze Transportwege und Verzicht auf Pflanzenschutzmittel während des Anbaus, hervorragende CO2- Bilanz


Der Gänsepeter
Rommerskirchen-Ramrath / Rhein-Kreis Neuss

Entfernung:		26 km
Die Macher*innen:	Peter Eßer & Familie
Die Erfahrung:		seit rund 25 Jahren auf qualitativ hochwertige Geflügelprodukte spezialisiert

Die Erzeugnisse:
- Gillbach-Gans, Gillbach-Hahn, Gillbach-Ente, hausgemachte Geflügelspezialitäten
- tiergerechte Haltung mit großzügigen Auslaufflächen
- ausgewogene Ernährung mit Mais und Getreide eigener Erzeugung
- gentechnikfreie und rein pflanzliche Ernährung
- langsames Wachstum
- hofeigene Schlachtung


Kartoffelkult
Rommerskirchen/Rhein-Kreis Neuss

Entfernung: 		35km
Die Macher*innen:	Heinrich Trippen & Familie
Die Erfahrung:		Familienbetrieb in vierter Generation geführt

Die Erzeugnisse:
- alte Kartoffelsorten neu entdeckt
- zur Zeit wachsen auf den Feldern acht verschiedene Sorten
- alle Kartoffeln werden im Umkreis von maximal zehn Kilometern vom Hof angebaut
- Anbau im Freiland
- unbehandeltes Saatgut
- Ernte erfolgt zum Teil in Handarbeit
- Qualität steht stets im Vordergrund
