---
name: provision server

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "server/**"

jobs:
  prepare-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Run Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: deploy.yml
          # Optional, directory where playbooks live
          directory: ./server
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            49.12.74.139 ansible_connection=ssh ansible_user=root ansible_python_interpreter=/usr/bin/python3
          # Optional, additional flags to pass to ansible-playbook
          options: |
            --verbose
